# Centralized Logging Configuration
# All modules log to a single master file with different levels

default_level: INFO

layers:
  # Main application log - everything goes here
  APP:
    level: DEBUG
    destinations:
      - type: file
        path: "workflow_logs/centralized/app.log"
        max_size: "50MB"
        backup_count: 10
      - type: console
        level: INFO
  
  # Critical errors only
  CRITICAL:
    level: ERROR
    destinations:
      - type: file
        path: "workflow_logs/centralized/errors.log"
        max_size: "10MB"
        backup_count: 5
      - type: console
        level: ERROR