codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

github_checks:
  annotations: true
