default_level: DEBUG
layers:
  default:
    level: DEBUG
    destinations:
    - type: console
      level: null
      path: null
      max_size: 5MB
      backup_count: 3
      format: colored
      use_colors: true
      url: null
      connection_string: null
      queue_url: null
      service_type: null
      credentials: null
      retry_count: 3
      retry_delay: 1.0
      timeout: 30.0
      max_connections: 10
      max_queue_size: 10000
      extra: null
    - type: file
      level: null
      path: managed_app.log
      max_size: 10MB
      backup_count: 5
      format: json-lines
      use_colors: true
      url: null
      connection_string: null
      queue_url: null
      service_type: null
      credentials: null
      retry_count: 3
      retry_delay: 1.0
      timeout: 30.0
      max_connections: 10
      max_queue_size: 10000
      extra: null
    color: null
    enabled: true
  error:
    level: ERROR
    destinations:
    - type: file
      level: null
      path: error.log
      max_size: 5MB
      backup_count: 3
      format: json-lines
      use_colors: true
      url: null
      connection_string: null
      queue_url: null
      service_type: null
      credentials: null
      retry_count: 3
      retry_delay: 1.0
      timeout: 30.0
      max_connections: 10
      max_queue_size: 10000
      extra: null
    color: null
    enabled: true
  debug:
    level: DEBUG
    destinations:
    - type: file
      level: null
      path: debug.log
      max_size: 5MB
      backup_count: 2
      format: fast-plain
      use_colors: true
      url: null
      connection_string: null
      queue_url: null
      service_type: null
      credentials: null
      retry_count: 3
      retry_delay: 1.0
      timeout: 30.0
      max_connections: 10
      max_queue_size: 10000
      extra: null
    color: null
    enabled: true
layer_colors: null
enable_security: true
enable_sanitization: false
enable_plugins: false
enable_performance_monitoring: false
security_level: medium
monitoring_detail_level: basic
monitoring_sample_rate: 100
monitoring_background: true
base_log_dir: null
log_dir_name: null
buffer_size: 8192
flush_interval: 1.0
